import 'dart:async';

import 'package:device_preview/device_preview.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:get/get.dart';

import 'package:villas_qatar/Core/constants/stripe_config.dart';
import 'package:villas_qatar/Core/services/deep_link_service.dart';
import 'package:villas_qatar/Core/services/push_notification_service.dart';
import 'package:villas_qatar/Core/services/storage_service.dart';

import 'package:villas_qatar/modules/home/service/UtilsController.dart';
import 'package:villas_qatar/modules/home/service/loaction_controller.dart';
import 'package:villas_qatar/modules/onboard/views/splash_screen.dart';

import 'core/localization/app_translation.dart';
import 'core/theme/app_theme.dart';
import 'core/utils/responsive.dart';

// Generated by FlutterFire CLI
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ------------------------------------------------------------
  // Storage
  // ------------------------------------------------------------
  await StorageService.init();

  // ------------------------------------------------------------
  // Firebase
  // ------------------------------------------------------------
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ------------------------------------------------------------
  // Firebase Cloud Messaging
  // ------------------------------------------------------------
  FirebaseMessaging.onBackgroundMessage(
    firebaseMessagingBackgroundHandler,
  );

  await PushNotificationService.initialize();

  // Register current FCM token.
  // unawaited prevents delaying app startup.
  unawaited(
    PushNotificationService.registerCurrentToken(),
  );

  // ------------------------------------------------------------
  // Stripe
  // ------------------------------------------------------------
  Stripe.publishableKey = StripeConfig.publishableKey;

  if (StripeConfig.merchantIdentifier.isNotEmpty) {
    Stripe.merchantIdentifier =
        StripeConfig.merchantIdentifier;
  }

  await Stripe.instance.applySettings();

  // ------------------------------------------------------------
  // Global GetX Controllers
  // ------------------------------------------------------------
  Get.put(
    Utilscontroller(),
    permanent: true,
  );

  Get.put(
    LocationController(),
    permanent: true,
  );

  // ------------------------------------------------------------
  // Start App
  // ------------------------------------------------------------
  runApp(
    DevicePreview(
      enabled: false,
      builder: (context) => const VillasQatarApp(),
    ),
  );
}

// ============================================================================
// APP
// ============================================================================

class VillasQatarApp extends StatefulWidget {
  const VillasQatarApp({super.key});

  @override
  State<VillasQatarApp> createState() => _VillasQatarAppState();
}

class _VillasQatarAppState extends State<VillasQatarApp> {
  // --------------------------------------------------------------------------
  // INIT
  // --------------------------------------------------------------------------

  @override
  void initState() {
    super.initState();

    // Initialize deep links after GetMaterialApp's navigator is available.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      DeepLinkService.initialize();
    });
  }

  // --------------------------------------------------------------------------
  // DISPOSE
  // --------------------------------------------------------------------------

  @override
  void dispose() {
    DeepLinkService.dispose();
    super.dispose();
  }

  // --------------------------------------------------------------------------
  // SAVED LOCALE
  // --------------------------------------------------------------------------

  Locale? _savedLocale() {
    final String? saved =
        StorageService.getSavedLanguageOrNull();

    if (saved == 'ar') {
      return const Locale('ar', 'QA');
    }

    if (saved == 'en') {
      return const Locale('en', 'US');
    }

    return null;
  }

  // --------------------------------------------------------------------------
  // BUILD
  // --------------------------------------------------------------------------

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        // ----------------------------------------------------------
        // Responsive Design Size
        // ----------------------------------------------------------

        final Size designSize;

        if (Responsive.isDesktop(context)) {
          designSize = const Size(1440, 1024);
        } else if (Responsive.isTablet(context)) {
          designSize = const Size(760, 1024);
        } else {
          designSize = const Size(394, 852);
        }

        // ----------------------------------------------------------
        // ScreenUtil
        // ----------------------------------------------------------

        return ScreenUtilInit(
          designSize: designSize,
          minTextAdapt: true,
          splitScreenMode: true,
          builder: (_, child) {
            return GetMaterialApp(
              // ----------------------------------------------------
              // Basic Configuration
              // ----------------------------------------------------

              debugShowCheckedModeBanner: false,

              title: 'Villas Qatar',

              useInheritedMediaQuery: true,

              // ----------------------------------------------------
              // Localization
              // ----------------------------------------------------

              locale:
                  DevicePreview.locale(context) ??
                  _savedLocale(),

              translations: AppTranslations(),

              fallbackLocale:
                  const Locale('en', 'US'),

              supportedLocales: const [
                Locale('en', 'US'),
                Locale('ar', 'QA'),
              ],

              localizationsDelegates: const [
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
              ],

              // ----------------------------------------------------
              // App Builder
              // ----------------------------------------------------

              builder: (context, child) {
                child = DevicePreview.appBuilder(
                  context,
                  child,
                );

                final Locale locale =
                    Get.locale ??
                    DevicePreview.locale(context) ??
                    const Locale('en', 'US');

                return Directionality(
                  textDirection:
                      locale.languageCode == 'ar'
                          ? TextDirection.rtl
                          : TextDirection.ltr,
                  child:
                      child ??
                      const SizedBox.shrink(),
                );
              },

              // ----------------------------------------------------
              // Theme
              // ----------------------------------------------------

              theme: AppTheme.lightTheme,

              // ----------------------------------------------------
              // Initial Screen
              // ----------------------------------------------------

              home: const SplashScreen(),
            );
          },
        );
      },
    );
  }
}